/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tbb_blue_utils_JniUtils */

#ifndef _Included_com_loveyou_miyuan_utils_JniUtils
#define _Included_com_loveyou_miyuan_utils_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_loveyou_miyuan_utils_JniUtils
 * Method:    getStringC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_loveyou_miyuan_utils_JniUtils_getStringC
  (JNIEnv *, jclass);

JNIEXPORT jstring JNICALL Java_com_loveyou_miyuan_utils_JniUtils_getToken
        (JNIEnv *, jclass);

/*
 * Class:     com_loveyou_miyuan_utils_JniUtils
 * Method:    myEncrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_loveyou_miyuan_utils_JniUtils_myEncrypt
  (JNIEnv *, jclass, jstring,jstring);

JNIEXPORT jstring JNICALL Java_com_loveyou_miyuan_utils_JniUtils_myOldEncrypt
        (JNIEnv *, jclass, jstring,jstring);

/*
 * Class:     com_loveyou_miyuan_utils_JniUtils
 * Method:    myDecrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_loveyou_miyuan_utils_JniUtils_myDecrypt
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
